# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1
  
jobs:
  build:
    docker: 
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - run: npm i
      - run: npm run lint
  test:
    docker: 
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - npm i
      - run: npm run test
  analyze:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - run: npm run audit



      

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build
      - test:
          requires: [build]
      - analyze:
          requires: [test]